=== lprisan/tabloro/prolog/kb_in.dtd
<?xml version="1.0"?>
<!ELEMENT board (context, goals, content, columns)>
<!ELEMENT context (#PCDATA)>
<!ELEMENT goals (goal*)>
<!ELEMENT goal (#PCDATA)>
<!ELEMENT content (#PCDATA)>
<!ELEMENT columns (column+)>
<!ELEMENT column ((csw-technique, aba-css-task, aba-css-team, aba-css-tec1, aba-css-tec2, 
                                  abb-css-task, abb-css-team, abb-css-tec1, abb-css-tec2) | EMPTY)> 
<!ELEMENT csw-technique (call-for-suggestion | (technique-name, technique-phase))>
<!ELEMENT technique-name (#PCDATA)>
<!ELEMENT technique-phase (#PCDATA)>
<!ELEMENT aba-css-task (call-for-suggestion | #PCDATA | EMPTY)>
<!ELEMENT aba-css-team (call-for-suggestion | #PCDATA | EMPTY)>
<!ELEMENT aba-css-tec1 (call-for-suggestion | #PCDATA | EMPTY)>
<!ELEMENT aba-css-tec2 (call-for-suggestion | #PCDATA | EMPTY)>
<!ELEMENT abb-css-task (call-for-suggestion | #PCDATA | EMPTY)>
<!ELEMENT abb-css-team (call-for-suggestion | #PCDATA | EMPTY)>
<!ELEMENT abb-css-tec1 (call-for-suggestion | #PCDATA | EMPTY)>
<!ELEMENT abb-css-tec2 (call-for-suggestion | #PCDATA | EMPTY)>
<!ELEMENT call-for-suggestion EMPTY>
<!ATTLIST column id CDATA #REQUIRED>
<!ATTLIST column hasStar (true|false) "false">

=== lprisan/tabloro/prolog/kb_in_1.xml
<?xml version="1.0"?><!DOCTYPE board SYSTEM "kb_in.dtd"><board><context>Thisisatextdescribingthecontext</context><goals><goal>Thisisatextdescribingagoal</goal><goal>Thisisatextdescribinganothergoal</goal></goals><content>Thisisatextdescribingsomecontent</content><columns><column id="1"><csw-technique><call-for-suggestion /></csw-technique><aba-css-task><call-for-suggestion /></aba-css-task><aba-css-team/><aba-css-tec1/><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column><column id="2"><csw-technique><technique-name/><technique-phase/></csw-technique><aba-css-task/><aba-css-team/><aba-css-tec1/><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column><column id="3"><csw-technique><technique-name/><technique-phase/></csw-technique><aba-css-task/><aba-css-team/><aba-css-tec1/><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column><column id="4"><csw-technique><technique-name/><technique-phase/></csw-technique><aba-css-task/><aba-css-team/><aba-css-tec1/><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column></columns></board>

=== lprisan/tabloro/prolog/testCases/wrong20170510-01.xml
<?xml version="1.0"?>
<!DOCTYPE board SYSTEM "kb_in.dtd">
<board>
  <context>...</context>
  <goals>
    <goal>...</goal>
  </goals>
  <content>...</content>
  <columns>
    <column id="1">
      <csw-technique>
        <technique-name></technique-name>
        <technique-phase>0</technique-phase>
      </csw-technique>
      <aba-css-task></aba-css-task>
      <aba-css-team></aba-css-team>
      <aba-css-tec1>FORUM</aba-css-tec1>
      <aba-css-tec2></aba-css-tec2>
      <abb-css-task></abb-css-task>
      <abb-css-team></abb-css-team>
      <abb-css-tec1></abb-css-tec1>
      <abb-css-tec2></abb-css-tec2>
    </column>
    <column id="2">
      <csw-technique>
        <technique-name></technique-name>
        <technique-phase>0</technique-phase>
      </csw-technique>
      <aba-css-task></aba-css-task>
      <aba-css-team></aba-css-team>
      <aba-css-tec1></aba-css-tec1>
      <aba-css-tec2></aba-css-tec2>
      <abb-css-task></abb-css-task>
      <abb-css-team></abb-css-team>
      <abb-css-tec1></abb-css-tec1>
      <abb-css-tec2></abb-css-tec2>
    </column>
    <column id="3">
      <csw-technique>
        <technique-name></technique-name>
        <technique-phase>0</technique-phase>
      </csw-technique>
      <aba-css-task></aba-css-task>
      <aba-css-team></aba-css-team>
      <aba-css-tec1></aba-css-tec1>
      <aba-css-tec2></aba-css-tec2>
      <abb-css-task></abb-css-task>
      <abb-css-team></abb-css-team>
      <abb-css-tec1></abb-css-tec1>
      <abb-css-tec2></abb-css-tec2>
   </column>
   <column id="4">
      <csw-technique>
        <technique-name></technique-name>
        <technique-phase>0</technique-phase>
      </csw-technique>
      <aba-css-task></aba-css-task>
      <aba-css-team></aba-css-team>
      <aba-css-tec1></aba-css-tec1>
      <aba-css-tec2></aba-css-tec2>
      <abb-css-task></abb-css-task>
      <abb-css-team></abb-css-team>
      <abb-css-tec1></abb-css-tec1>
      <abb-css-tec2></abb-css-tec2>
   </column>
  </columns>
</board>

=== lprisan/tabloro/prolog/testCases/AC/PeerReview.xml
<?xml version="1.0"?><!DOCTYPE board SYSTEM "kb_in.dtd"><board><context>This is a text describing the context</context><goals><goal>This is a text describing a goal</goal><goal>This is a text describing another goal</goal></goals><content>This is a text describing some content</content><columns><column id="1"><csw-technique><technique-name>PEER REVIEW _ PHASE I</technique-name><technique-phase>1</technique-phase></csw-technique><aba-css-task>STUDYING</aba-css-task><aba-css-team>INDIVIDUAL LEARNERS</aba-css-team><aba-css-tec1>SELECTED STUDY MATERIALS</aba-css-tec1><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column><column id="2"><csw-technique><technique-name/><technique-phase/></csw-technique><aba-css-task>PRODUCING AN ARTEFACT </aba-css-task><aba-css-team>PAIRS</aba-css-team><aba-css-tec1>MATERIALS AND TOOLS FOR PRACTICE</aba-css-tec1><aba-css-tec2>FORUM</aba-css-tec2><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column><column id="3"><csw-technique><technique-name>PEER REVIEW _ PHASE II</technique-name><technique-phase>2</technique-phase></csw-technique><aba-css-task>COMMENTING ON SOMEONE ELSE’S WORK</aba-css-task><aba-css-team>INDIVIDUAL LEARNERS</aba-css-team><aba-css-tec1>FORUM</aba-css-tec1><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column><column id="4"><csw-technique><technique-name>PEER REVIEW _ PHASE III</technique-name><technique-phase>3</technique-phase></csw-technique><aba-css-task>PRODUCING AN ARTEFACT </aba-css-task><aba-css-team>PAIRS</aba-css-team><aba-css-tec1>MATERIALS AND TOOLS FOR PRACTICE</aba-css-tec1><aba-css-tec2>FORUM</aba-css-tec2><abb-css-task>GIVING A PRESENTATION</abb-css-task><abb-css-team>PLENARY</abb-css-team><abb-css-tec1>VIDEOCONFERENCING SYSTEM</abb-css-tec1><abb-css-tec2/></column></columns></board>

=== lprisan/tabloro/prolog/testCases/FP&DP/23.xml
<?xml version="1.0"?>
<!DOCTYPE board SYSTEM "kb_in.dtd">
<board>
    <context>This is a text describing the context</context>
    <goals>
        <goal>This is a text describing a goal</goal>
        <goal>This is a text describing another goal</goal>
    </goals>
    <content>This is a text describing some content</content>
    <columns>
        <column id="1">
            <csw-technique><technique-name/><technique-phase/></csw-technique>
            <aba-css-task><call-for-suggestion/></aba-css-task>
            <aba-css-team>INDIVIDUAL LEARNERS</aba-css-team><aba-css-tec1/><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column>
        <column id="2">
            <csw-technique><technique-name/><technique-phase/></csw-technique><aba-css-task/><aba-css-team/><aba-css-tec1/><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column>
        <column id="3">
            <csw-technique><technique-name/><technique-phase/></csw-technique><aba-css-task/><aba-css-team/><aba-css-tec1/><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column>
        <column id="4">
            <csw-technique><technique-name/><technique-phase/></csw-technique><aba-css-task/><aba-css-team/><aba-css-tec1/><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column>
    </columns>
</board>

=== lprisan/tabloro/prolog/testCases/AC/Jigsaw.xml
<?xml version="1.0"?><!DOCTYPE board SYSTEM "kb_in.dtd"><board><context>This is a text describing the context</context><goals><goal>This is a text describing a goal</goal><goal>This is a text describing another goal</goal></goals><content>This is a text describing some content</content><columns><column id="1"><csw-technique><technique-name>JIGSAW _ PHASE I _EXPERT GROUPS_</technique-name><technique-phase>1</technique-phase></csw-technique><aba-css-task>STUDYING</aba-css-task><aba-css-team>INDIVIDUAL LEARNERS</aba-css-team><aba-css-tec1>SELECTED STUDY MATERIALS</aba-css-tec1><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column><column id="2"><csw-technique><technique-name/><technique-phase/></csw-technique><aba-css-task>PREPARING A PRESENTATION</aba-css-task><aba-css-team>SMALL GROUPS</aba-css-team><aba-css-tec1>PRESENTATION SOFTWARE</aba-css-tec1><aba-css-tec2>NO TECHNOLOGY</aba-css-tec2><abb-css-task>GIVING A PRESENTATION</abb-css-task><abb-css-team>PLENARY</abb-css-team><abb-css-tec1>PROJECTOR</abb-css-tec1><abb-css-tec2/></column><column id="3"><csw-technique><technique-name>JIGSAW _ PHASE II _JIGSAW GROUPS_</technique-name><technique-phase>2</technique-phase></csw-technique><aba-css-task>WRITING A REPORT</aba-css-task><aba-css-team>SMALL GROUPS</aba-css-team><aba-css-tec1>TEXT EDITOR</aba-css-tec1><aba-css-tec2>NO TECHNOLOGY</aba-css-tec2><abb-css-task>GIVING A PRESENTATION</abb-css-task><abb-css-team>PLENARY</abb-css-team><abb-css-tec1>PROJECTOR</abb-css-tec1><abb-css-tec2/></column><column id="4"><csw-technique><technique-name/><technique-phase/></csw-technique><aba-css-task/><aba-css-team/><aba-css-tec1/><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column></columns></board>

=== lprisan/tabloro/prolog/testCases/AC/DiscussionArtifact.xml
<?xml version="1.0"?><!DOCTYPE board SYSTEM "kb_in.dtd"><board><context>This is a text describing the context</context><goals><goal>This is a text describing a goal</goal><goal>This is a text describing another goal</goal></goals><content>This is a text describing some content</content><columns><column id="1"><csw-technique><technique-name>DISCUSSION _ PHASE I _ALL CASES_</technique-name><technique-phase>1</technique-phase></csw-technique><aba-css-task>FINDING MATERIALS</aba-css-task><aba-css-team>INDIVIDUAL LEARNERS</aba-css-team><aba-css-tec1>SOURCE OF MATERIALS FOR LEARNING</aba-css-tec1><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column><column id="2"><csw-technique><technique-name/><technique-phase/></csw-technique><aba-css-task>DEBATING</aba-css-task><aba-css-team/><aba-css-tec1>NO TECHNOLOGY</aba-css-tec1><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column><column id="3"><csw-technique><technique-name/><technique-phase/></csw-technique><aba-css-task/><aba-css-team/><aba-css-tec1/><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column><column id="4"><csw-technique><technique-name>DISCUSSION _TOWARDS ARTEFACT_ _ PHASE II</technique-name><technique-phase>2</technique-phase></csw-technique><aba-css-task>PRODUCING AN ARTEFACT </aba-css-task><aba-css-team>SMALL GROUPS</aba-css-team><aba-css-tec1>MATERIALS AND TOOLS FOR PRACTICE</aba-css-tec1><aba-css-tec2>NO TECHNOLOGY</aba-css-tec2><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column></columns></board>

=== lprisan/tabloro/prolog/testCases/AC/PyramidList.xml
<?xml version="1.0"?><!DOCTYPE board SYSTEM "kb_in.dtd"><board><context>This is a text describing the context</context><goals><goal>This is a text describing a goal</goal><goal>This is a text describing another goal</goal></goals><content>This is a text describing some content</content><columns><column id="1"><csw-technique><technique-name>PYRAMID _FOR LIST PREPARATION_ _ PHASE I</technique-name><technique-phase>1</technique-phase></csw-technique><aba-css-task>STUDYING</aba-css-task><aba-css-team>INDIVIDUAL LEARNERS</aba-css-team><aba-css-tec1>SELECTED STUDY MATERIALS</aba-css-tec1><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column><column id="2"><csw-technique><technique-name/><technique-phase/></csw-technique><aba-css-task>PREPARING A LIST OF QUESTIONS</aba-css-task><aba-css-team>INDIVIDUAL LEARNERS</aba-css-team><aba-css-tec1>TEXT EDITOR</aba-css-tec1><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column><column id="3"><csw-technique><technique-name>PYRAMID _FOR LIST PREPARATION_ _ PHASE II</technique-name><technique-phase>2</technique-phase></csw-technique><aba-css-task>PREPARING A LIST OF QUESTIONS</aba-css-task><aba-css-team>SMALL GROUPS</aba-css-team><aba-css-tec1>TEXT EDITOR</aba-css-tec1><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column><column id="4"><csw-technique><technique-name>PYRAMID _FOR LIST PREPARATION_ _ PHASE III</technique-name><technique-phase>3</technique-phase></csw-technique><aba-css-task>PREPARING A LIST OF QUESTIONS</aba-css-task><aba-css-team>PLENARY</aba-css-team><aba-css-tec1>TEXT EDITOR</aba-css-tec1><aba-css-tec2/><abb-css-task/><abb-css-team/><abb-css-tec1/><abb-css-tec2/></column></columns></board>
