=== lprisan/tabloro/prolog/kb_out.dtd
<?xml version="1.0"?>
<!ELEMENT kb-response (inconsistent-slots, missing-cards, suggested-cards)>
<!ELEMENT inconsistent-slots position*, rationale?>
<!ELEMENT missing-cards cards>
<!ELEMENT suggested-cards cards>
<!ELEMENT cards ((ground-card | alternative)*, rationale?)>
<!ELEMENT ground-card ((technique-card | task-card | team-card | technology-card), position?)>
<!ELEMENT technique-card (technique-name, technique-phase)>
<!ELEMENT technique-name (#PCDATA)>
<!ELEMENT technique-phase (#PCDATA)>
<!ELEMENT task-card (#PCDATA)>
<!ELEMENT team-card (#PCDATA)>
<!ELEMENT technology-card (#PCDATA)>
<!ELEMENT alternative ((technique-card | task-card | team-card | technology-card)*, position?)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT rationale (#PCDATA)>

=== lprisan/tabloro/prolog/testCases/FP&DP/kb_out_09.xml
<?xml version="1.0"?>
<!DOCTYPE kb-response SYSTEM "kb_out.dtd">
<!--
  Warning on the empty Task C1-ABB-CSS-TASK
  Team: Individual learners
 -->
<kb-response>
  <inconsistent-slots>
  </inconsistent-slots>
  <missing-cards>
    <cards>
      <alternative>
        <position>C1-ABB-CSS-TASK</position>
      </alternative>
    </cards>
  </missing-cards>
  <suggested-cards>
    <cards>
      <ground-card>
        <team-card>INDIVIDUAL LEARNERS</team-card>
        <position>C2-ABA-CSS-TEAM</position>
      </ground-card>
    </cards>
  </suggested-cards>
</kb-response>

=== lprisan/tabloro/prolog/testCases/FP&DP/kb_out_15.xml
<?xml version="1.0"?>
<!DOCTYPE kb-response SYSTEM "kb_out.dtd">
<!--
  ERROR: combinations are right, but  the cluster Preparing a presentation+Small groupd+Forum
  must be placed in Column 2 (because Task 1 lasts 1 week)
 -->
<kb-response>
  <inconsistent-slots>
     <position>C1-ABB-CSS-TASK</position>
     <position>C1-ABB-CSS-TEAM</position>
     <position>C1-ABB-CSS-TEC1</position>
  </inconsistent-slots>
  <missing-cards>
    <cards>
    </cards>
  </missing-cards>
  <suggested-cards>
    <cards>
    </cards>
  </suggested-cards>
</kb-response>

=== lprisan/tabloro/prolog/testCases/FP&DP/kb_out_03.xml
<?xml version="1.0"?>
<!DOCTYPE kb-response SYSTEM "kb_out.dtd">
<!--
  Studying
-->
<kb-response>
  <inconsistent-slots>
  </inconsistent-slots>
  <missing-cards>
    <cards>
    </cards>
  </missing-cards>
  <suggested-cards>
    <cards>
      <ground-card>
        <task-card>STUDYING</task-card>
      </ground-card>
      <position>C1-ABA-CSS-TASK</position>
    </cards>
  </suggested-cards>
</kb-response>

=== lprisan/tabloro/prolog/testCases/FP&DP/kb_out_14.xml
<?xml version="1.0"?>
<!DOCTYPE kb-response SYSTEM "kb_out.dtd">
<!--
  ERROR:  Plenary cannot be associated with Preparing a presentation
 -->
<kb-response>
   <inconsistent-slots>
      <position>C2-ABA-CSS-TASK</position>
      <position>C2-ABA-CSS-TEAM</position>
  </inconsistent-slots>
  <missing-cards>
    <cards>
    </cards>
  </missing-cards>
  <suggested-cards>
    <cards>
    </cards>
  </suggested-cards>
</kb-response>

=== lprisan/tabloro/prolog/testCases/FP&DP/kb_out_02.xml
<?xml version="1.0"?>
<!DOCTYPE kb-response SYSTEM "kb_out.dtd">
<!--
  All Techniques – Phases I
-->
<kb-response>
  <inconsistent-slots>
  </inconsistent-slots>
  <missing-cards>
    <cards>
    </cards>
 </missing-cards>
  <suggested-cards>
    <cards>
      <alternative>
        <technique-card>
          <technique-name>JIGSAW - PHASE I (EXPERT GROUPS)</technique-name>
          <technique-phase>1</technique-phase>
        </technique-card>
        <technique-card>
          <technique-name>PEER REVIEW - PHASE I</technique-name>
          <technique-phase>1</technique-phase>
	</technique-card>
        <technique-card>
          <technique-name>CASE STUDY - PHASE I</technique-name>
          <technique-phase>1</technique-phase>
        </technique-card>
        <technique-card>
          <technique-name>PYRAMID (FOR LIST PREPARATION) - PHASE I</technique-name>
          <technique-phase>1</technique-phase>
        </technique-card>
        <technique-card>
          <technique-name>PYRAMID (FOR PROBLEM SOLVING) - PHASE I</technique-name>
          <technique-phase>1</technique-phase>
        </technique-card>
        <technique-card>
          <technique-name>DISCUSSION - PHASE I (ALL CASES)</technique-name>
          <technique-phase>1</technique-phase>
        </technique-card>
        <technique-card>
          <technique-name>ROLE PLAY - PHASE I</technique-name>
          <technique-phase>1</technique-phase>
        </technique-card>
        <position>C1-CSW-TECHNIQUE</position>
      </alternative>
    </cards>
  </suggested-cards>
</kb-response>

=== lprisan/tabloro/prolog/testCases/FP&DP/kb_out_16.xml
<?xml version="1.0"?>
<!DOCTYPE kb-response SYSTEM "kb_out.dtd">
<!--
  ERROR: Jigsaw – Phase II is needed
 -->
<kb-response>
  <inconsistent-slots>
     <position>C1-CSW-TECHNIQUE</position>
     <position>C2-CSW-TECHNIQUE</position>
  </inconsistent-slots>
  <missing-cards>
    <cards>
    </cards>
  </missing-cards>
  <suggested-cards>
    <cards>
    </cards>
  </suggested-cards>
</kb-response>

=== lprisan/tabloro/prolog/testCases/FP&DP/kb_out_24.xml
<?xml version="1.0"?>
<!DOCTYPE kb-response SYSTEM "kb_out.dtd">
<!--
  Writing a repeor, studying, finding materials, preparing a list of questions,
  commenting on someone else’s work, preparing a presentation, carrying out an assignement,
  producing an artifact
 -->
<kb-response>
  <inconsistent-slots>
  </inconsistent-slots>
  <missing-cards>
    <cards>
    </cards>
  </missing-cards>
  <suggested-cards>
    <cards>
      <alternative>
        <task-card>WRITING A REPORT</task-card>
        <task-card>STUDYING</task-card>
        <task-card>FINDING MATERIALS</task-card>
        <task-card>PREPARING A LIST OF QUESTIONS</task-card>
        <task-card>COMMENTING ON SOMEONE ELSE’S WORK</task-card>
        <task-card>PREPARING A PRESENTATION</task-card>
        <task-card>CARRYING OUT AN ASSIGNMENT</task-card>
        <task-card>PRODUCING AN ARTEFACT</task-card>
        <position>C1-ABA-CSS-TASK</position>
      </alternative>
    </cards>
  </suggested-cards>
</kb-response>

=== lprisan/tabloro/prolog/kb_out_sample_01.xml
<?xml version="1.0"?>
<!DOCTYPE kb-response SYSTEM "kb_out.dtd">
<!--
  "fake typical response structure"
  This is an example of the data structure the KB returns
  from a call to semantic_check.
  Suppose the users have placed in 1st column, upper rows:
  - a "Pyramid I" technique card (slot C1-CSW)
  - a "Study" task card (slot C1-ABA-CSS-TASK)
  - an "Individual learner" team card (slot C1-ABA-CSS-TEAM)
  - a "Forum" card (slot C1-ABA-CSS-TEC1)
  - a "Text editor" card (slot C1-ABA-CSS-TEC2)
  The board complies with the semantic rules of the KB, so the
  <inconsistent-cards> section of the response is empty.
  The board is incomplete because the second task of Pyramid I
  is missing, as well as the whole 2nd phase of the technique.
  The detected missing cards are:
  - a "Solve a problem" OR a "Prepare a list of questions"
    task card in 1st column, lower row (slot C1-ABB-CSS-TASK);
    the associated team and technology cards are not reported
    to the users.
  - a "Pyramid II" technique card in 2nd column (slot C2-CSW)
  As no "?" cards were present in the board status, the
  <suggested-cards> section is empty.
-->
<kb-response>
  <inconsistent-slots>
   </inconsistent-slots>
  <missing-cards>
    <cards>
      <alternative>
        <task-card>solve a problem</task-card>
        <task-card>prepare a list of questions</task-card>
        <position>C1-ABB-CSS-TASK</position>
      </alternative>
      <ground-card>
        <technique-card>
          <technique-name>Pyramid</technique-name>
          <technique-phase>2</technique-phase>
        </technique-card>
        <position>C2-CSW-TECHNIQUE</position>
      </ground-card>
    </cards>
  </missing-cards>
  <suggested-cards>
    <cards>
    </cards>
  </suggested-cards>
</kb-response>
