=== lprisan/tabloro/prolog/kb_out.dtd
<?xml version="1.0"?>
<!ELEMENT kb-response (inconsistent-slots, missing-cards, suggested-cards)>
<!ELEMENT inconsistent-slots position*, rationale?>
<!ELEMENT missing-cards cards>
<!ELEMENT suggested-cards cards>
<!ELEMENT cards ((ground-card | alternative)*, rationale?)>
<!ELEMENT ground-card ((technique-card | task-card | team-card | technology-card), position?)>
<!ELEMENT technique-card (technique-name, technique-phase)>
<!ELEMENT technique-name (#PCDATA)>
<!ELEMENT technique-phase (#PCDATA)>
<!ELEMENT task-card (#PCDATA)>
<!ELEMENT team-card (#PCDATA)>
<!ELEMENT technology-card (#PCDATA)>
<!ELEMENT alternative ((technique-card | task-card | team-card | technology-card)*, position?)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT rationale (#PCDATA)>

=== lprisan/tabloro/prolog/testCases/FP&DP/kb_out_22.xml
<?xml version="1.0"?>
<!DOCTYPE kb-response SYSTEM "kb_out.dtd">
<!--
  Warning: missing Teams and Technologies in Column 1
  All tasks are possible
 -->
<kb-response>
  <inconsistent-slots>
   </inconsistent-slots>
  <missing-cards>
    <cards>
      <alternative>
        <position>C1-ABA-CSS-TEAM</position>
      </alternative>
      <alternative>
        <position>C1-ABA-CSS-TEC1</position>
      </alternative>
    </cards>
  </missing-cards>
  <suggested-cards>
    <cards>
      <alternative>
        <task-card>WRITING A REPORT</task-card>
        <task-card>STUDYING</task-card>
        <task-card>FINDING MATERIALS</task-card>
        <task-card>PREPARING A LIST OF QUESTIONS</task-card>
        <task-card>COMMENTING ON SOMEONE ELSE’S WORK</task-card>
        <task-card>PREPARING A PRESENTATION</task-card>
        <task-card>CARRYING OUT AN ASSIGNMENT</task-card>
        <task-card>GIVING A PRESENTATION</task-card>
        <task-card>SOLVING A PROBLEM</task-card>
        <task-card>INTERVIEWING AN EXPERT</task-card>
        <task-card>ASSUMING ROLES</task-card>
        <task-card>PRODUCING AN ARTEFACT</task-card>
        <task-card>DEBATING</task-card>
        <position>C2-ABA-CSS-TASK</position>
      </alternative>
    </cards>
  </suggested-cards>
</kb-response>

=== lprisan/tabloro/prolog/testCases/FP&DP/kb_out_08.xml
<?xml version="1.0"?>
<!DOCTYPE kb-response SYSTEM "kb_out.dtd">
<!--
  --- soprassedere --- Warning on the empty Task c2-ABA-CSS-Task
  Team: Individual learners or Pairs or Small groups
 -->
<kb-response>
  <inconsistent-slots>
  </inconsistent-slots>
  <missing-cards>
    <cards>
<!-- SOPRASSEDERE
<alternative>
        <position>C2-ABA-CSS-TASK</position>
      </alternative>
SOPRASSEDERE -->
    </cards>
  </missing-cards>
  <suggested-cards>
    <cards>
      <alternative>
        <team-card>INDIVIDUAL LEARNERS</team-card>
        <team-card>PAIRS</team-card>
        <team-card>SMALL GROUPS</team-card>
        <position>C2-ABA-CSS-TEAM</position>
      </alternative>
    </cards>
  </suggested-cards>
</kb-response>

=== lprisan/tabloro/prolog/testCases/FP&DP/kb_out_05.xml
<?xml version="1.0"?>
<!DOCTYPE kb-response SYSTEM "kb_out.dtd">
<!--
  Selected study materials 
-->
<kb-response>
  <inconsistent-slots>
  </inconsistent-slots>
  <missing-cards>
    <cards>
    </cards>
  </missing-cards>
  <suggested-cards>
    <cards>
      <ground-card>
        <technology-card>SELECTED STUDY MATERIALS</technology-card>
      </ground-card>
      <position>C1-ABA-CSS-TEC1</position>
    </cards>
  </suggested-cards>
</kb-response>

=== lprisan/tabloro/prolog/testCases/FP&DP/kb_out_04.xml
<?xml version="1.0"?>
<!DOCTYPE kb-response SYSTEM "kb_out.dtd">
<!--
  Individual learners 
-->
<kb-response>
  <inconsistent-slots>
  </inconsistent-slots>
  <missing-cards>
    <cards>
    </cards>
  </missing-cards>
  <suggested-cards>
    <cards>
      <ground-card>
        <team-card>INDIVIDUAL LEARNERS</team-card>
      </ground-card>
      <position>C1-ABA-CSS-TEAM</position>
    </cards>
  </suggested-cards>
</kb-response>

=== lprisan/tabloro/prolog/testCases/FP&DP/kb_out_25.xml
<?xml version="1.0"?>
<!DOCTYPE kb-response SYSTEM "kb_out.dtd">
<!--
  Discussion phase i all cases
 -->
<kb-response>
  <inconsistent-slots>
  </inconsistent-slots>
  <missing-cards>
    <cards>
    </cards>
  </missing-cards>
  <suggested-cards>
    <cards>
      <ground-card>
        <technique-card>DISCUSSION - PHASE I (ALL CASES)</technique-card>
        <position>C1-CSW-TECHNIQUE</position>
      </ground-card>
    </cards>
  </suggested-cards>
</kb-response>

=== lprisan/tabloro/prolog/testCases/FP&DP/kb_out_10.xml
<?xml version="1.0"?>
<!DOCTYPE kb-response SYSTEM "kb_out.dtd">
<!--
  Warning on the empty Task C1-ABA-CSS-TASK
  Phase II:  Discussion towards assignment or Discussion towards artefatc or Discussion towards report
 -->
<kb-response>
  <inconsistent-slots>
  </inconsistent-slots>
  <missing-cards>
    <cards>
      <alternative>
         <position>C1-ABA-CSS-TASK</position>
     </alternative>
    </cards>
  </missing-cards>
  <suggested-cards>
    <cards>
      <alternative>
        <technique-card>DISCUSSION (TOWARDS ASSIGNMENT) - PHASE II</technique-card>
        <technique-card>DISCUSSION (TOWARDS ARTEFACT) - PHASE II</technique-card>
        <technique-card>DISCUSSION (TOWARDS REPORT) - PHASE II</technique-card>
        <position>C2-CSW-TECHNIQUE</position>
      </alternative>
    </cards>
  </suggested-cards>
</kb-response>

=== lprisan/tabloro/prolog/testCases/FP&DP/kb_out_11.xml
<?xml version="1.0"?>
<!DOCTYPE kb-response SYSTEM "kb_out.dtd">
<!--
  Warning on the empty Task C1-ABA-CSS-TASK
  Technique: empty cell
 -->
<kb-response>
  <inconsistent-slots>
  </inconsistent-slots>
  <missing-cards>
    <cards>
      <alternative>
        <position>C1-ABA-CSS-TASK</position>
      </alternative>
    </cards>
  </missing-cards>
  <suggested-cards>
    <cards>
      <ground-card>
        <technique-card />
        <position>C2-CSW-TECHNIQUE</position>
      </ground-card>
    </cards>
  </suggested-cards>
</kb-response>
